### ISSUE TITLE
Run single workload on multicore

### ISSUE THREAD

**Issue by manaal22152** [ChampSim/ChampSim#111]
I want to run a single workload on 4 core configuration. Is it possible using ChampSim?

**Comment by ngober** [comment]
Have you tried running a 4-core configuration with four copies of the same trace?

**Comment by manaal22152** [comment]
That would be running 4 workloads on 4-cores. I want to run a single workload on 4 -core for calculation of weighted IPC.

**Comment by ngober** [comment]
ChampSim, being a trace-based simulator, needs one trace per core. Otherwise, cores will sit entirely idle while the others run. If you were to run a single core in a 4-core simulation, it would be no different than a 1-core simulation. Currently, ChampSim fails to run if fewer traces than cores are given.

**Comment by manaal22152** [comment]
Thanks a lot!
