### ISSUE TITLE
Interpretation of Avg. ROB Occupancy at Branch Mispredict 

### ISSUE THREAD

**Issue by varungohil** [ChampSim/ChampSim#139]
Can we interpret the Avg. ROB Occupancy at Branch Mispredict metric reported by ChampSim as the number of instructions that will be squashed because of the misprediction? What are common usecases for this metric?

**Comment by sethpugsley** [comment]
This stat is supposed to represent how much work is left in the ROB at the time of branch misprediction.  Because ChampSim is trace-driven, there are never any wrong-path instructions in the ROB, so there's nothing to actually flush.  Instead, it's how many instructions the OoO engine can comb through to try to find useful work to do while waiting for the mispredicted branch to be executed, at which time instruction fetch resumes, and the ROB can begin filling up again.

This number kind of sheds light on the performance benefit that improved branch prediction affords.  However, if the back end is super fast at executing and retiring instructions, then this number might still be very low, even if the branch predictor is very accurate.
