### ISSUE TITLE
Physical or virtual address 

### ISSUE THREAD

**Issue by mahmoodn** [ChampSim/ChampSim#15]
I would like to know if the trace gets physical or virtual address from PIN?

**Comment by itisntalex** [comment]
Even though that issue is a bit aged, I will propose an answer to it here.

If you go into the [ooo_cpu.cc](https://github.com/ChampSim/ChampSim/blob/6956933bd4cc4dbe196c7af99fbb626dc2792f47/src/ooo_cpu.cc#L1407) at line 1407 you'll see that when an instruction in the ROB is added to the store queue, the `virtual_address` field is filled from the matching ROB entry. You can see such behaviour for other queues on the file.

Then if you look in the method in charge of reading instructions from traces, you'll see that the ROB entries are filled directly from the traces without conversion. So you can deduce that the tracer does trace virtual memory addresses.
