### ISSUE TITLE
error in applications with avx instrctions.

### ISSUE THREAD

**Issue by TOMsworkspace** [ChampSim/ChampSim#244]
When I use champsim to generate traces for an application which uses AVX instrctions, I get an error:
E: Instruction memory operand does not have a size (vgatherdpd zmm2, k7, qword ptr [r14+ymm27*8])

How could i fix it?

pin: 3.22
OS: ubuntu 18.04

**Comment by ngober** [comment]
It appears that (PIN breaks when calling INS_MemoryOperandSize() for scatter/gather instructions)[https://software.intel.com/sites/landingpage/pintool/docs/98547/Pin/html/group__INS__INSPECTION.html#gaa905931fcdcac481c789192e0bd30014], because their memory operands do not have trivial sizes. This is definitely an issue to consider in the long term, but it shouldn't affect the operation of ChampSim as it currently stands.

Try checking out the `tracer_update` branch, to see if that works. If it does, then at least we can call it okay in the short-term.

**Comment by TOMsworkspace** [comment]
OK, I also find the reason in the pin document which can be seen [here](https://software.intel.com/sites/landingpage/pintool/docs/98484/Pin/html/group__INS__INSPECTION.html#gaa905931fcdcac481c789192e0bd30014). 

So I add these code to skip trace for AVX instrctions, and it works now.

Add these code in the start of function "VOID Instruction(INS ins, VOID *v)" in the champsim_tracer.cpp line 312:

//skip the scattered memory access instructions.
if(INS_HasScatteredMemoryAccess(ins)) return;

//skip the vgather/vscatter 
if(INS_IsVgather(ins) || INS_IsVscatter(ins)) return;
