### ISSUE TITLE
LD_WIDTH should be consumed separately for DTLB and L1D

### ISSUE THREAD

**Issue by sawansib** [ChampSim/ChampSim#264]
Hi,

in the master branch, ooo_cpu.cc file in the function call operate_lsq() why the load_issued is not reset to 0 after the DTLB access?

In the current version of the code in the master branch if we have an LD_WIDTH of 2 for example, then it means if the RTL0 has 2 entries we will never do any L1D cache access in that cycle as load_issued < LQ_WIDTH will return false. This is not totally correct as DTLB and the L1D are pipelined so it means that the processor should be able to do 2 DTLB access and 2 L1D. 

If you agree the simple solution will be to reset the load_issue after the DTLB access. 

Sawan

**Comment by ngober** [comment]
There are two things to say about this: First, the demand stream of the DTLB is significantly more sparse than the demand stream of the L1D, since the former operates on a page granularity and the latter on a block granularity, so the increased latency imposed from bandwidth contention is likely not significant. Second, this has changed significantly on the develop branch, where the TLB accesses happen in parallel with the cache accesses. Would you look at the development branch to see if it resolves your issue?
