### ISSUE TITLE
"victim_addr" parameter of "CACHE::upadate_replacement_state" is not getting any value!!!

### ISSUE THREAD

**Issue by Shafayet-Anik** [ChampSim/ChampSim#268]
Hi,
"victim_addr" parameter of "CACHE::upadate_replacement_state" is not getting any value!!! It's always printing zero. That means victim addresses are not passing to victim_addr!! It should get a value if any of the "way" of a set is evicted.

**Comment by ngober** [comment]
Hmm... That sure does look like a bug to me. I've issued a patch that will resolve this. It's based on the development branch, since `CACHE::filllike_miss()` has changed enough to cause a merge conflict. If you need it applied to the master branch, you'll need to cherry pick it out.

I'm waiting to merge this until it can be tested, but this is a good find nevertheless.
