### ISSUE TITLE
How can I make OPT (Belady) experiment result??

### ISSUE THREAD

**Issue by yhj27** [ChampSim/ChampSim#302]
Hello, I'm researching in cache replacement policy with Champsim.

Many paper shows experiment result including OPT algorithm, but I don't know how to make it.

I cannot find any file of OPT replacement in Champsim.

Is there anyone who can help me??

**Comment by ngober** [comment]
Belady's optimal replacement chooses as a victim the block that will be referenced most distantly in the future. In order to implement this, you need full knowledge of the future, which ChampSim does not provide. In theory, you could analyze a trace file, then embed the predictions into the replacement policy, but this is not supported out of the box.
