### ISSUE TITLE
how to collect the  cloudsuite  traces?

### ISSUE THREAD

**Issue by huster-ckc** [ChampSim/ChampSim#39]
how to collect the  cloudsuite  traces?
thanks

**Comment by GinoAC** [comment]
Are you trying to download the already available cloudsuite traces or generate new cloudsuite traces using Pin?

**Comment by huster-ckc** [comment]
> Are you trying to download the already available cloudsuite traces or generate new cloudsuite traces using Pin?

I want generate new cloudsuite traces using Pin .I think it's different from spec using pin.I hope you can give me some suggestions. Thank you for your reply

**Comment by ngober** [comment]
The only difference between the cloudsuite traces and the current trace format is the inclusion of an `uint8_t asid[2]` field. If you want to generate traces that use this format, you would only need to modify the tracer to fill in this field. However, I'll warn that support for the cloudsuite traces has atrophied somewhat since they were used. Reviving support for ASIDs is on the development roadmap, but it probably will not happen soon.
