### ISSUE TITLE
issue with vspkg istall/update

### ISSUE THREAD

**Issue by hamadah10** [ChampSim/ChampSim#522]
![image](https://github.com/user-attachments/assets/2fc2921e-f1fb-44f1-80f0-53a98c1f9423)

Helllo, 
I am trying to get champsim downloaded in an ubuntu environment. Yet, Once I get to the point of updating my vspkg, I get this error on the screen shot that I don't know what to do to solve.. here is the command I used to do that : 

![image](https://github.com/user-attachments/assets/210e0d63-7693-4c9b-a300-68d0721a08f4)

anyone can provide any idea on how to solve this?

**Comment by ngober** [comment]
It looks like something is very wrong with your git information, like if you somehow deleted the `.git/` directory. Git is telling you that there are untracked files with the same name as the files in the ChampSim repository. This is probably because your local checkout of ChampSim doesn't know it's git-controlled. However that happened, this does not appear to be a problem with ChampSim.
