### ISSUE TITLE
Possible bug in MSHR match

### ISSUE THREAD

**Issue by mahmoodn** [ChampSim/ChampSim#68]
Hi
Part of the [handle_read()](https://github.com/ChampSim/ChampSim/blob/master/src/cache.cc#L638) for checking a miss block in MSHR seems to be buggy. The code is
```
                // check mshr
                uint8_t miss_handled = 1;
                int mshr_index = check_mshr(&RQ.entry[index]);

		if(mshr_index == -2)
		  {
		    // this is a data/instruction collision in the MSHR, so we have to wait before we can allocate this miss
		    miss_handled = 0;
		  }
```
So, if we find a match the `mshr_index` must be -2. That means, upon a match, [check_mshr()](https://github.com/ChampSim/ChampSim/blob/master/src/cache.cc#L1654) must return -2. Now look at part of the code:

```
  for (uint32_t index=0; index<MSHR_SIZE; index++)
    {
      if (MSHR.entry[index].address == packet->address)
	{
	      return index;
	}
    }
```
So, that function, returns index upon a match and not -2. 
In fact [return -2](https://github.com/ChampSim/ChampSim/blob/master/src/cache.cc#L1681) is commented in that function.

That can be verified easily by debugging. I see that there is a match in the MSHR and the function returns 0 (first entry in MSHR) but that is considered as collision.

Any comment on that? If you agree with that, I will create a poll request.

**Comment by ngober** [comment]
I don't think that's what returning -2 means in this context. The -2 return was introduced during preparations for IPC1, to resolve instruction-data collisions by waiting for one to return before demanding the other. I'm pretty sure this was resolved before IPC1, then trimmed up in #51, where we just return both instead of one or the other. When the `check_mshr()` function returns nonnegative, it indicates a match in the given MSHR index.
